### ISSUE TITLE
does not compile with 3.2.0-rc

### ISSUE THREAD

**Issue by sledorze** [gcanti/fp-ts-routing#34]
Error is:
```typescript
src/index.ts:102:25 - error TS2345: Argument of type 'Formatter<A & B & Record<Extract<keyof B, keyof A>, never>>' is not assignable to parameter of type 'Formatter<A & B>'.
  Types of property 'run' are incompatible.
    Type '(r: Route, a: A & B & Record<Extract<keyof B, keyof A>, never>) => Route' is not assignable to type '(r: Route, a: A & B) => Route'.
      Types of parameters 'a' and 'a' are incompatible.
        Type 'A & B' is not assignable to type 'A & B & Record<Extract<keyof B, keyof A>, never>'.
          Type 'A & B' is not assignable to type 'Record<Extract<keyof B, keyof A>, never>'.

102     return new Match(p, f)
```

pointing to:
https://github.com/gcanti/fp-ts-routing/blob/master/src/index.ts#L102
